# Generated by Django 4.0.4 on 2022-12-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phase_name', models.CharField(max_length=10)),
                ('Phase_location', models.CharField(max_length=10)),
                ('Starting_date', models.DateTimeField()),
                ('Ending_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-Ending_date', '-Starting_date'],
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Road_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phase')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Cars', 'Cars'), ('Utility', 'Utility'), ('Microbus', 'Microbus'), ('Minibus', 'Minibus'), ('Large buses', 'Large buses'), ('Light Truck', 'Light Truck'), ('Medium Truck', 'Medium Truck'), ('Heavy Truck', 'Heavy Truck'), ('Trailer and Trailer Trucks', 'Trailer and Trailer Trucks'), ('Bicycle', 'Bicycle'), ('Tempo', 'Tempo')], max_length=100)),
                ('vehicle_image', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spot_name', models.CharField(max_length=50)),
                ('Spot_code', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Roads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roads')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
