# Generated by Django 4.0.4 on 2022-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_counting_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='Traffic_countings',
            field=models.IntegerField(null=True),
        ),
    ]
