# Generated by Django 4.0.4 on 2023-01-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vehicle_options_rename_roads_spots_road'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['created']},
        ),
    ]
