# Generated by Django 4.0.4 on 2023-01-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counting',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['Starting_date']},
        ),
        migrations.AlterModelOptions(
            name='roads',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='spots',
            options={'ordering': ['created']},
        ),
    ]
