# Generated by Django 4.0.4 on 2022-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
